// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfSTeSvpXTZ15oFOqDDGEECFODYN1EFRE',
    appId: '1:447013867772:web:5342e4fe7dd53b98ce4779',
    messagingSenderId: '447013867772',
    projectId: 'smartracking-37ccf',
    authDomain: 'smartracking-37ccf.firebaseapp.com',
    storageBucket: 'smartracking-37ccf.firebasestorage.app',
    measurementId: 'G-23JQ62XJDR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAae3nky-9xaRVcHUE-VAhozsPPTCjt0k',
    appId: '1:447013867772:android:7c793cf9ef3d3ef1ce4779',
    messagingSenderId: '447013867772',
    projectId: 'smartracking-37ccf',
    storageBucket: 'smartracking-37ccf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqHddzx3hGEu7amo7f0bSSdDrnwyYlI2s',
    appId: '1:447013867772:ios:7a33db5bdb0d383ece4779',
    messagingSenderId: '447013867772',
    projectId: 'smartracking-37ccf',
    storageBucket: 'smartracking-37ccf.firebasestorage.app',
    iosBundleId: 'com.smart.tracking.smartTacking',
  );

}